spring.datasource.url=jdbc:mysql://localhost:3306/automotivo_db
spring.datasource.username=root
spring.datasource.password=Lucas2210
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port= 8081



